Fix form renderer in project_template
Numigi/odoo-project-addons pull request #101
Opened 2019-11-26 19:36 UTC by ddufresne

Only apply the new modifiers for project.task.
Otherwise, these modifiers can be applied on other models which leads to a stack trace.

2019-11-26 21:09 UTC, foutoucour requested changes

2019-11-26 21:09 UTC, foutoucour commented on project_template/static/src/js/modifiers.js
> +        if (this.state.model === "project.task"){
Il nous faut des tests pour Javascript. L'impact a été large sur la dernière MEP.
Une update de project a mis down le CRM.

2019-11-28 16:34 UTC, ddufresne commented
@foutoucour in the last commit, I reduced the complexity of the javascript file (Less code == less bugs).

I suggest we can go on with this PR, and figure out a more global solution with integration tests.

2019-11-28 20:21 UTC, foutoucour approved these changes

2019-11-28 20:21 UTC, merged