add project_group_create (TA#20672)
Numigi/odoo-project-addons pull request #118
Opened 2020-04-08 18:38 UTC by foutoucour

2020-04-08 18:44 UTC, ddufresne requested changes

2020-04-08 18:44 UTC, ddufresne commented on project_group_create/models/project.py
> +            raise AccessError(_('You are not allowed to create a project.'))
@foutoucour pas besoin de code python ici. Ceci est une règle simple.

Tu peux simplement créer un extended.security.rule:
https://github.com/Numigi/odoo-product-addons/blob/12.0/product_create_group/security/extended_security_rule.xml

2020-04-08 18:44 UTC, ddufresne commented on project_group_create/views/project_project.xml
> +</odoo>
enlever ce fichier

2020-04-08 18:44 UTC, ddufresne commented on project_group_create/views/project_task.xml
> +</openerp>
enlever ce fichier

2020-04-08 18:44 UTC, ddufresne commented on project_group_create/views/project_task_type.xml
> +</openerp>
enlever ce fichier

2020-04-08 18:44 UTC, ddufresne commented on project_group_create/README.rst
> +This module prevents the quick creation of project stages.
Il faut mettre à jour le README

2020-04-08 19:13 UTC, foutoucour commented on project_group_create/views/project_project.xml
> +</odoo>
done :)

2020-04-08 19:13 UTC, foutoucour commented on project_group_create/views/project_task.xml
> +</openerp>
done :)

2020-04-08 19:13 UTC, foutoucour commented on project_group_create/views/project_task_type.xml
> +</openerp>
done :)

2020-04-08 19:13 UTC, foutoucour commented on project_group_create/README.rst
> +This module prevents the quick creation of project stages.
done :)

2020-04-08 19:15 UTC, foutoucour commented on project_group_create/models/project.py
> +            raise AccessError(_('You are not allowed to create a project.'))
J'ai testé avec un XML et je n'ai pas réussi a avoir le résultat voulu.
Mon approche était de mettre perm_create=0 mais pas d'effet j'ai l'impression.

Sauf si tu vois un bloquant à utiliser la version python, j'aimerai avancer sur le ticket. C'est un puit à temps ce ticket :)

Laisse moi savoir

2020-04-20 14:49 UTC, ddufresne requested changes

2020-04-20 14:49 UTC, ddufresne commented on project_group_create/README.rst
> +When you install the module, the group of project manager is not allowed anymore
```suggestion
When you install the module, the group of project manager is not allowed
```

2020-04-20 14:49 UTC, ddufresne commented on project_group_create/security/ir.model.access.csv
> +project_manager_create,Project / Manager With Create: Access Recordings,project.model_project_project,group_project_manager_create,1,1,1,0
Ce fichier csv n'est pas requis. Le nouveau groupe hérite du groupe Projet / Gestionnaire.

2020-04-20 14:49 UTC, ddufresne commented on project_group_create/security/res_groups.xml
> +        <field name="users" eval="[(4, ref('base.user_admin'))]"/>
```suggestion
        <field name="users" eval="[(4, ref('base.user_admin'), (4, ref('base.user_root'))]"/>
```

2020-04-20 16:20 UTC, foutoucour commented on project_group_create/security/ir.model.access.csv
> +project_manager_create,Project / Manager With Create: Access Recordings,project.model_project_project,group_project_manager_create,1,1,1,0
done :)

2020-04-20 16:50 UTC, ddufresne approved these changes

2020-04-20 16:50 UTC, merged