TA#22544 Add module timesheet_task_project_no_change
Numigi/odoo-project-addons pull request #125
Opened 2020-04-16 21:36 UTC by ddufresne

2020-04-16 21:52 UTC, foutoucour requested changes

2020-04-16 21:52 UTC, foutoucour commented on timesheet_task_project_no_change/models/project_task.py
> +    def _check_has_no_timesheet(self):
J'ai plus l'impression que ces fonctions vérifient si la tâche a une feuille de temps non ?

2020-04-17 12:31 UTC, ddufresne commented on timesheet_task_project_no_change/models/project_task.py
> +    def _check_has_no_timesheet(self):
@foutoucour la fonction vérifie que la tâche n'a pas de feuille de temps.

Si la tâche a une feuille de temps, une erreur est levée.

2020-04-17 16:26 UTC, foutoucour approved these changes

2020-04-20 14:46 UTC, merged