TA#36850 add project_kanban_dates module
Numigi/odoo-project-addons pull request #181
Opened 2021-09-16 20:59 UTC by gabgosrob

2021-09-20 15:40 UTC, ddufresne commented
@gabgosrob il y a un autre module project_task_ids dans tes commits.

Aussi, il manque les traductions.

2021-09-20 15:41 UTC, ddufresne requested changes
Retirer le module superflu.
Ajouter les traductions.

2021-09-21 17:53 UTC, gabgosrob commented
Le module est enlevé mais je pense bien que le fichier de traductions est là, il n'y à que le mot 'Start' à traduire si je ne me trompe pas.

2021-09-21 18:29 UTC, ddufresne approved these changes

2021-09-21 18:29 UTC, merged