Add project_time_management (TA#6156)
Numigi/odoo-project-addons pull request #21
Opened 2018-11-27 22:53 UTC by foutoucour

https://isidor.numigi.net/web#id=6156&view_type=form&model=project.task&action=298&menu_id=200

2018-11-27 22:53 UTC, foutoucour commented on project_time_range/views/project_project.xml
> +                    <group name="left" string="Estimated">
j'avais oublié le titre du groupe

2018-11-27 22:54 UTC, foutoucour commented on project_time_management/views/project_project.xml
> +                <group name="right" string="Calculated">
@ddufresne 
Est ce que tu pourrais m'aider ici. Comment est ce que je peux placer ce groupe à droite du groupe de field qui sont dans `project_time_range`?

Merci

2018-11-27 22:56 UTC, ddufresne commented on project_time_management/tests/test_project_project.py
> +from odoo.exceptions import ValidationError
![Codacy](https://app.codacy.com/assets/images/favicon.png) Issue found: [Unused ValidationError imported from odoo.exceptions](https://app.codacy.com/app/numigi/odoo-project-addons/pullRequest?prid=2637635)

2018-11-28 15:37 UTC, ddufresne requested changes

2018-11-28 15:37 UTC, ddufresne commented on project_time_management/views/project_project.xml
> +                <group name="right" string="Calculated">
@foutoucour Il faut un groupe parent pour contenir les groupes Management et Calculated.

2018-11-28 15:37 UTC, ddufresne commented on project_time_management/models/project_project.py
> +class ProjectTaskWithMinAndMaxHours(models.Model):
le nom de la classe est erronné

2018-11-28 15:37 UTC, ddufresne commented on project_time_management/README.md
> +* Numigi (tm) and all its contributors (https://bit.ly/numigiens)
le contenu du README n'est pas à jour

2018-11-28 16:22 UTC, foutoucour commented on project_time_management/views/project_project.xml
> +                <group name="right" string="Calculated">
done

2018-11-28 16:32 UTC, foutoucour commented on project_time_management/models/project_project.py
> +class ProjectTaskWithMinAndMaxHours(models.Model):
fait

2018-11-28 16:32 UTC, foutoucour commented on project_time_management/README.md
> +* Numigi (tm) and all its contributors (https://bit.ly/numigiens)
fait

2018-11-28 18:35 UTC, ddufresne approved these changes
@foutoucour nickel, un commentaire non bloquant

2018-11-28 18:35 UTC, ddufresne commented on project_time_management/tests/test_project_project.py
> +        assert expected_value == self.project_a.__getattribute__(field)
dans odoo, tu peux accéder aux attributs par clé:

self.project_a[field]

2018-11-28 19:35 UTC, foutoucour commented on project_time_management/tests/test_project_project.py
> +        assert expected_value == self.project_a.__getattribute__(field)
Merci pour l'info.

Si ça te gène pas, je garde la version "pythonic" :)

2018-11-28 19:36 UTC, merged

2018-11-28 19:50 UTC, ddufresne commented on project_time_management/tests/test_project_project.py
> +        assert expected_value == self.project_a.__getattribute__(field)
pas de problème :)