TA#50621 [ADD] project_task_kanban_sequence_fixed: locking column on …
Numigi/odoo-project-addons pull request #310
Opened 2023-02-22 08:09 UTC by lanto-razafindrabe

Locking column on kanban view of project task model

2023-02-22 15:30 UTC, majouda requested changes

2023-02-22 15:30 UTC, majouda commented on project_task_kanban_sequence_fixed/static/src/js/kanban_column.js
> +                alert(_t("Oups! You can not sort columns order here in this view."));
Hello @lanto-razafindrabe 

Peut on faire en sorte de juste annuler l'opération sans afficher le message d'erreur. 
Sinon le code me semble bien :D

2023-02-22 16:09 UTC, majouda requested changes

2023-02-22 16:09 UTC, majouda commented on project_task_kanban_sequence_fixed/__manifest__.py
> +    'maintainer': 'Numigi',
peux tu ajouter le siteweb aussi. Merci

2023-02-23 07:00 UTC, lanto-razafindrabe commented on project_task_kanban_sequence_fixed/static/src/js/kanban_column.js
> +                alert(_t("Oups! You can not sort columns order here in this view."));
Hello @majouda 

Ça marche ! :wink: je vais voir ça.

2023-02-23 07:00 UTC, lanto-razafindrabe commented on project_task_kanban_sequence_fixed/__manifest__.py
> +    'maintainer': 'Numigi',
Oki doki

2023-03-01 20:32 UTC, majouda approved these changes

2023-03-01 20:32 UTC, merged