Add module analytic_line_revenue
Numigi/odoo-project-addons pull request #59
Opened 2019-06-10 16:16 UTC by ddufresne

https://isidor.numigi.net/web#id=9016&view_type=form&model=project.task&menu_id=200

2019-06-10 16:19 UTC, ddufresne commented on analytic_line_revenue/journal_entry_propagation.py
> +from odoo import fields, models
![Codacy](https://app.codacy.com/assets/images/favicon.png) Issue found: [Unused fields imported from odoo](https://app.codacy.com/app/numigi/odoo-project-addons/pullRequest?prid=3698257)

2019-06-10 23:50 UTC, foutoucour requested changes
Pourquoi ces noms de fichiers? 
Pourquoi ne pas avoir utiliser les standard `account_move_line.py` et `account_analytic_line.py`?

2019-06-11 12:57 UTC, ddufresne commented
@foutoucour bonne question. J'ai pris l'habitude de placer les champs dans un même fichier models. Ça permet de rapidement voir qu'est-ce qui est ajouté au modèle relationnel.

J'ai un fichier journal_entry_propagation.py et un fichier test_journal_entry_propagation.py.
Pour moi, c'est une fonctionnalité isolée.
Si éventuellement, le module avait 2 fonctionnalités, je créerais 2 autres fichiers.

Ici, ça a l'air un peu trivial car il y a un seul modèle par fichier.
Sur des modules plus complexes, ça fait toute la différence. Par exemple:
https://github.com/Numigi/odoo-project-addons/tree/11.0/project_outsourcing

Je peux renommer les fichiers si tu préfères.

2019-06-11 12:59 UTC, foutoucour approved these changes

2019-06-11 13:02 UTC, merged