add project_stage_allow_timesheet (TA#12111)
Numigi/odoo-project-addons pull request #63
Opened 2019-06-13 21:55 UTC by foutoucour

https://isidor.numigi.net/web#id=12111&view_type=form&model=project.task&action=298&menu_id=200

2019-06-13 21:57 UTC, ddufresne commented on project_stage_allow_timesheet/__manifest__.py
> +{
![Codacy](https://app.codacy.com/assets/images/favicon.png) Issue found: [Duplicate key 'license' in dictionary](https://app.codacy.com/app/numigi/odoo-project-addons/pullRequest?prid=3718665)

2019-06-14 13:18 UTC, ddufresne requested changes
@foutoucour il faudrait aussi des tests pour les 2 contraintes.

2019-06-14 13:18 UTC, ddufresne commented on project_stage_allow_timesheet/README.md
> +*It is not forbidden to move a time sheet into another task if the project does not allow time sheets.*
@foutoucour mineur, c'est très discutable.

Dernièrement, je me suis tourné vers rst pour les README.

1. Ça évite de faire chialer les logs de Odoo (plein de warnings lorsqu'on utilise markdown).
2. Ça permet d'avoir une table des matières super facilement.

2019-06-14 13:18 UTC, ddufresne commented on project_stage_allow_timesheet/models/account_analytic_line.py
> +    @api.one
api.one est deprecated, malheureusement

2019-06-14 13:18 UTC, ddufresne commented on project_stage_allow_timesheet/models/account_analytic_line.py
> +            "(Task: %s, Project: %s, Project Stage: %s)"
plus bas tu utilises .format au lieu de %s.

L'un comme l'autre ne me dérange pas, mais c'est mieux d'être constant dans un même fichier python.

2019-06-14 15:19 UTC, foutoucour commented
@ddufresne fait ;)

2019-06-14 15:48 UTC, ddufresne approved these changes

2019-06-14 15:48 UTC, merged