[11.0] Preparation step on consumption route
Numigi/odoo-project-addons pull request #82
Opened 2019-09-13 17:13 UTC by ddufresne

https://isidor.numigi.net/web#action=292&active_id=448&model=project.task&view_type=kanban&menu_id=200

2019-09-13 17:18 UTC, ddufresne commented on project_wip_material/task_picking_smart_button.py
> +            return_picking = pickings.filtered(lambda p: _is_preparation_return_picking(p))
![Codacy](https://app.codacy.com/assets/images/favicon.png) Issue found: [Lambda may not be necessary](https://app.codacy.com/app/numigi/odoo-project-addons/pullRequest?prid=4160521)

2019-09-16 14:49 UTC, foutoucour requested changes

2019-09-16 14:49 UTC, foutoucour commented on project_wip_material/consumption_route.py
> +        description = (
y a un détail d'implementation ici. Avec l'approche actuel, on a l'impression que `StockPickingType` sait ce que va faire `WarehouseWithPickingStep` puisque `TWO_STEPS_DESCRIPTION` n'est connu que dans `WarehouseWithPickingStep`. Il y a une faiblesse aussi si, pour une raison x, on a une 3ème description. Alors `StockPickingType` serait affecté sans raison.

Je verrai bien la logique autour de `description` soit plutôt dissociée de `_get_consumption_route_values`. Un champ calculé peut être.

Qu'est ce que tu en dis ?

2019-09-16 14:49 UTC, foutoucour commented on project_wip_material/consumption_route.py
> +        require_prep_type = self.consu_steps == 'two_steps'
cette logique se retrouve à plusieurs place. Il serait intéressant de l'extraire dans une fonction.

2019-09-16 14:49 UTC, foutoucour commented on project_wip_material/task_picking_smart_button.py
> +    return picking_type == picking_type.warehouse_id.consu_prep_return_type_id
mettre `picking_type.warehouse_id.consu_prep_return_type_id` dans une variable rendrait le code plus lisible

2019-09-16 14:51 UTC, foutoucour commented
@ddufresne Le lien dans la description de la PR amène au lot. Dans quelle tâche je devrait mettre mon temps de review (Note pour moi: 22 mins)

2019-09-16 15:20 UTC, ddufresne commented on project_wip_material/consumption_route.py
> +        description = (
@foutoucour tout à fait

2019-09-16 15:21 UTC, ddufresne commented on project_wip_material/consumption_route.py
> +        require_prep_type = self.consu_steps == 'two_steps'
En effet, je vais isoler le prédicat dans une fonction _has_two_step_consumption(warehouse).

Même chose pour le self.consu_steps == 'one_step'

2019-09-16 15:23 UTC, ddufresne reviewed
@foutoucour j'ai mis à jour le lien vers la tâche.

2019-09-16 15:23 UTC, ddufresne commented on project_wip_material/task_picking_smart_button.py
> +    return picking_type == picking_type.warehouse_id.consu_prep_return_type_id
:+1:

2019-09-17 15:32 UTC, ddufresne commented
@foutoucour j'ai amélioré le code, merci pour la review

2019-09-17 15:35 UTC, ddufresne commented on project_wip_material/consumption_route.py
> +    def _get_consumption_route_description(self):
![Codacy](https://app.codacy.com/assets/images/favicon.png) Issue found: [Method could be a function](https://app.codacy.com/app/numigi/odoo-project-addons/pullRequest?prid=4160521)

2019-09-17 15:50 UTC, foutoucour approved these changes
👍

2019-09-17 17:46 UTC, merged