Integrate project_template with subtasks and timesheets
Numigi/odoo-project-addons pull request #93
Opened 2019-10-31 19:46 UTC by ddufresne

https://isidor.numigi.net/web#id=16968&view_type=form&model=project.task&menu_id=200

2019-10-31 19:48 UTC, ddufresne commented on project_template/static/src/js/modifiers.js
> +    return node.tag === "field" && (node.attrs.name || "").startsWith("date")
![Codacy](https://app.codacy.com/assets/images/favicon.png) Issue found: [Missing semicolon. (semi)](https://app.codacy.com/app/numigi/odoo-project-addons/pullRequest?prid=4420733)

2019-10-31 19:48 UTC, ddufresne commented on project_template/models/project.py
> +    def _create_task_from_template(self, template):
![Codacy](https://app.codacy.com/assets/images/favicon.png) Issue found: [Method could be a function](https://app.codacy.com/app/numigi/odoo-project-addons/pullRequest?prid=4420733)

2019-10-31 19:48 UTC, ddufresne commented on project_template_timesheet/models/project_task.py
> +    def _get_values_for_invisible_template_fields(self):
![Codacy](https://app.codacy.com/assets/images/favicon.png) Issue found: [Method could be a function](https://app.codacy.com/app/numigi/odoo-project-addons/pullRequest?prid=4420733)

2019-10-31 19:48 UTC, ddufresne commented on project_template/static/src/js/modifiers.js
> +        invisibleAttribute && Boolean(eval(node.attrs.invisible_on_template))
![Codacy](https://app.codacy.com/assets/images/favicon.png) Issue found: [eval with argument of type MemberExpression (security/detect-eval-with-expression)](https://app.codacy.com/app/numigi/odoo-project-addons/pullRequest?prid=4420733)

2019-10-31 19:48 UTC, ddufresne commented on project_template/static/src/js/modifiers.js
> +        invisibleAttribute && Boolean(eval(node.attrs.invisible_on_template))
![Codacy](https://app.codacy.com/assets/images/favicon.png) Issue found: [eval can be harmful. (no-eval)](https://app.codacy.com/app/numigi/odoo-project-addons/pullRequest?prid=4420733)

2019-10-31 20:08 UTC, foutoucour requested changes

2019-10-31 20:08 UTC, foutoucour commented on project_remaining_hours_update/views/project_task.xml
> +                    invisible_on_template="1"
pourquoi `project_remaining_hours_update` a une intéraction/dépendance sur `project_template` ? C'est contre intuitif non ?

2019-10-31 20:08 UTC, foutoucour commented on project_template/models/project.py
> +        return template.copy({
Qu'est ce qu'il se passe si un champ requis est ajouté ?
Je sais que c'est pas une pratique que nous voulons, mais c'est un bloquant pour ce cas.
Il faudrait au moins mentionner le cas dans le README, pour nous, et puisque le dépôt est publique.

2019-10-31 20:25 UTC, ddufresne commented on project_remaining_hours_update/views/project_task.xml
> +                    invisible_on_template="1"
non, on cache le champ car il n'y a aucune interaction

2019-10-31 20:28 UTC, ddufresne commented on project_template/models/project.py
> +        return template.copy({
Si un champ obligatoire est ajouté, il est obligatoire aussi sur la tâche source, donc il y a une valeur sur la tâche source. Celle-ci est propagée du template vers la tâche.

Dans un cas de champ obligatoire avec copy=False, un tel champ briserait l'action Dupliquer. À ce moment, c'est un bug au niveau du module qui ajoute le champ.

2019-10-31 21:59 UTC, foutoucour commented on project_remaining_hours_update/views/project_task.xml
> +                    invisible_on_template="1"
Ça devrait être une modification du button qui s'opère dans project_template non ?
Ça reste bizarre d'avoir une référence d'un autre module qui n'est pas en dépendance, tu trouves pas ?

2019-10-31 21:59 UTC, foutoucour commented on project_template/models/project.py
> +        return template.copy({
👍

2019-11-01 12:13 UTC, ddufresne commented on project_remaining_hours_update/views/project_task.xml
> +                    invisible_on_template="1"
Je suis d'accord. Ce n'est pas idéal. Je vois 2 autres approches:

* Créer plusieurs modules de binding
     peut-être l'option la plus propre, mais on se retrouve avec pas mal de modules qui ajoutent un attribut.

* Créer un module sous isidor qui ajoute les attributs manquants
    Ceci est non industrialisable selon moi.

Je suis ouvert. Quelle approche te semblerait la meilleure?

2019-11-01 20:51 UTC, foutoucour commented on project_remaining_hours_update/views/project_task.xml
> +                    invisible_on_template="1"
Ouais pas simple.

Je pense préférer le module dans isidor.

C'est spécial d'avoir tous ces modules, peut être que seul isidor aura le cas. Et on fera un module si le cas se propage dans d'autres instances.

Ça te plait comme approche ?

2019-11-01 20:52 UTC, ddufresne commented on project_remaining_hours_update/views/project_task.xml
> +                    invisible_on_template="1"
oui, on y va comme ça.

2019-11-04 18:11 UTC, ddufresne commented
@foutoucour j'ai corrigé par rapport à ton dernier commentaire.

Je merge, mais si jamais tu as d'autres commentaires, n'hésite pas.

2019-11-04 18:11 UTC, merged