Add module project_task_link
Numigi/odoo-project-addons pull request #95
Opened 2019-11-11 17:52 UTC by ddufresne

https://www.numigi.com/web#id=17193&action=298&model=project.task&view_type=form&menu_id=200

2019-11-11 18:05 UTC, ddufresne commented on project_task_link/__init__.py
> +from . import models
![Codacy](https://app.codacy.com/assets/images/favicon.png) Issue found: ['.models' imported but unused](https://app.codacy.com/app/numigi/odoo-project-addons/pullRequest?prid=4478774)

2019-11-11 18:05 UTC, ddufresne commented on project_task_link/models/common.py
> +def _get_task_ref_regex(env: 'Environment') -> str:
![Codacy](https://app.codacy.com/assets/images/favicon.png) Issue found: [invalid syntax](https://app.codacy.com/app/numigi/odoo-project-addons/pullRequest?prid=4478774)

2019-11-11 18:05 UTC, ddufresne commented on project_task_link/static/src/js/html_field.js
> +var HtmlField = require('web_editor.backend').FieldTextHtmlSimple;
![Codacy](https://app.codacy.com/assets/images/favicon.png) Issue found: [Strings must use doublequote. (quotes)](https://app.codacy.com/app/numigi/odoo-project-addons/pullRequest?prid=4478774)

2019-11-11 18:05 UTC, ddufresne commented on project_task_link/models/__init__.py
> +from . import project_task
![Codacy](https://app.codacy.com/assets/images/favicon.png) Issue found: ['.project_task' imported but unused](https://app.codacy.com/app/numigi/odoo-project-addons/pullRequest?prid=4478774)

2019-11-11 18:05 UTC, ddufresne commented on project_task_link/static/src/js/html_field.js
> +        var taskLinks = this.$('a').filter(function() {
![Codacy](https://app.codacy.com/assets/images/favicon.png) Issue found: [Strings must use doublequote. (quotes)](https://app.codacy.com/app/numigi/odoo-project-addons/pullRequest?prid=4478774)

2019-11-11 18:05 UTC, ddufresne commented on project_task_link/static/src/js/html_field.js
> +odoo.define("project_task_link.html_field", function(require) {
![Codacy](https://app.codacy.com/assets/images/favicon.png) Issue found: ['odoo' is not defined. (no-undef)](https://app.codacy.com/app/numigi/odoo-project-addons/pullRequest?prid=4478774)

2019-11-11 18:05 UTC, ddufresne commented on project_task_link/models/common.py
> +from lxml import etree
![Codacy](https://app.codacy.com/assets/images/favicon.png) Issue found: [Using etree to parse untrusted XML data is known to be vulnerable to XML attacks. Replace etree with the equivalent defusedxml package.](https://app.codacy.com/app/numigi/odoo-project-addons/pullRequest?prid=4478774)

2019-11-11 18:05 UTC, ddufresne commented on project_task_link/static/src/js/html_field.js
> +                context: odoo.session_info.user_context,
![Codacy](https://app.codacy.com/assets/images/favicon.png) Issue found: ['odoo' is not defined. (no-undef)](https://app.codacy.com/app/numigi/odoo-project-addons/pullRequest?prid=4478774)

2019-11-12 16:23 UTC, foutoucour requested changes

2019-11-12 16:23 UTC, foutoucour commented on project_task_link/README.rst
> +This module allows to insert dynamic links in the descriptions of tasks.
```suggestion
This module allows to insert dynamic links in the description of tasks.
```

2019-11-12 16:23 UTC, foutoucour commented on project_task_link/tests/test_project_task.py
> +        "TA{}",
```suggestion
        "TA{}",
        "TA#{}",
```

2019-11-12 16:23 UTC, foutoucour commented on project_task_link/models/common.py
> +DEFAULT_TASK_REF_REGEX = r'[Tt][Aa]\#?\d+'
Je suis partagé sur cette implémentation. 
Je suis partagé car nous allons avoir besoin de la même logique pour Github PR à un moment,
et je trouve le tout compliqué.

Je comprends que ça permet l'utilisation d'un ir.config.parameter pour rendre custom la regex, mais est-ce la bonne manière de répondre au besoin, je ne suis pas sûr.

Je te propose un chat de 15-30 mins demain sur le sujet, ok ?

2019-11-12 21:59 UTC, ddufresne commented on project_task_reference/models/project_task.py
> +def _get_task_ref_regex(env: 'Environment') -> str:
![Codacy](https://app.codacy.com/assets/images/favicon.png) Issue found: [invalid syntax](https://app.codacy.com/app/numigi/odoo-project-addons/pullRequest?prid=4478774)

2019-11-12 21:59 UTC, ddufresne commented on project_task_reference/tests/test_project_task.py
> +    def _make_reference_from_task_id(self, task_id):
![Codacy](https://app.codacy.com/assets/images/favicon.png) Issue found: [Method could be a function](https://app.codacy.com/app/numigi/odoo-project-addons/pullRequest?prid=4478774)

2019-11-12 21:59 UTC, ddufresne commented on project_task_reference/__init__.py
> +from . import models
![Codacy](https://app.codacy.com/assets/images/favicon.png) Issue found: ['.models' imported but unused](https://app.codacy.com/app/numigi/odoo-project-addons/pullRequest?prid=4478774)

2019-11-12 21:59 UTC, ddufresne commented on project_task_link/models/common.py
> +def _find_task_references(env: 'Environment', text: str) -> List[TaskReference]:
![Codacy](https://app.codacy.com/assets/images/favicon.png) Issue found: [invalid syntax](https://app.codacy.com/app/numigi/odoo-project-addons/pullRequest?prid=4478774)

2019-11-12 21:59 UTC, ddufresne commented on project_task_reference/reference.py
> +    def __init__(self, values: Mapping[str, str], string: str, format_: str):
![Codacy](https://app.codacy.com/assets/images/favicon.png) Issue found: [invalid syntax](https://app.codacy.com/app/numigi/odoo-project-addons/pullRequest?prid=4478774)

2019-11-12 21:59 UTC, ddufresne commented on project_task_reference/models/project_task.py
> +from odoo import api, models, _
![Codacy](https://app.codacy.com/assets/images/favicon.png) Issue found: [Unused api imported from odoo](https://app.codacy.com/app/numigi/odoo-project-addons/pullRequest?prid=4478774)

2019-11-12 22:05 UTC, ddufresne commented on project_task_reference/__init__.py
> +from . import models
![Codacy](https://app.codacy.com/assets/images/favicon.png) Issue found: ['.models' imported but unused](https://app.codacy.com/app/numigi/odoo-project-addons/pullRequest?prid=4478774)

2019-11-12 22:05 UTC, ddufresne commented on project_task_reference/reference.py
> +    def __init__(self, values: Mapping[str, str], string: str, format_: str):
![Codacy](https://app.codacy.com/assets/images/favicon.png) Issue found: [invalid syntax](https://app.codacy.com/app/numigi/odoo-project-addons/pullRequest?prid=4478774)

2019-11-12 22:05 UTC, ddufresne commented on project_task_reference/models/project_task.py
> +def _get_task_ref_regex(env: 'Environment') -> str:
![Codacy](https://app.codacy.com/assets/images/favicon.png) Issue found: [invalid syntax](https://app.codacy.com/app/numigi/odoo-project-addons/pullRequest?prid=4478774)

2019-11-12 22:05 UTC, ddufresne commented on project_task_reference/tests/test_project_task.py
> +    def _make_reference_from_task_id(self, task_id):
![Codacy](https://app.codacy.com/assets/images/favicon.png) Issue found: [Method could be a function](https://app.codacy.com/app/numigi/odoo-project-addons/pullRequest?prid=4478774)

2019-11-12 22:05 UTC, ddufresne commented on project_task_link/models/common.py
> +def _find_task_references(env: 'Environment', text: str) -> List[TaskReference]:
![Codacy](https://app.codacy.com/assets/images/favicon.png) Issue found: [invalid syntax](https://app.codacy.com/app/numigi/odoo-project-addons/pullRequest?prid=4478774)

2019-11-12 22:05 UTC, ddufresne commented on project_task_reference/models/project_task.py
> +from odoo import api, models, _
![Codacy](https://app.codacy.com/assets/images/favicon.png) Issue found: [Unused api imported from odoo](https://app.codacy.com/app/numigi/odoo-project-addons/pullRequest?prid=4478774)

2019-11-13 14:10 UTC, foutoucour commented
@ddufresne ça fail :D

2019-11-13 14:18 UTC, ddufresne commented on project_task_link/models/common.py
> +def _find_task_references(env: 'Environment', text: str) -> List[TaskReference]:
![Codacy](https://app.codacy.com/assets/images/favicon.png) Issue found: [invalid syntax](https://app.codacy.com/app/numigi/odoo-project-addons/pullRequest?prid=4478774)

2019-11-13 14:18 UTC, ddufresne commented on project_task_reference/models/project_task.py
> +def _get_task_ref_regex(env: 'Environment') -> str:
![Codacy](https://app.codacy.com/assets/images/favicon.png) Issue found: [invalid syntax](https://app.codacy.com/app/numigi/odoo-project-addons/pullRequest?prid=4478774)

2019-11-13 14:18 UTC, ddufresne commented on project_task_reference/reference.py
> +    def __init__(self, values: Mapping[str, str], string: str, format_: str):
![Codacy](https://app.codacy.com/assets/images/favicon.png) Issue found: [invalid syntax](https://app.codacy.com/app/numigi/odoo-project-addons/pullRequest?prid=4478774)

2019-11-13 14:18 UTC, ddufresne commented on project_task_reference/tests/test_project_task.py
> +    def _make_reference_from_task_id(self, task_id):
![Codacy](https://app.codacy.com/assets/images/favicon.png) Issue found: [Method could be a function](https://app.codacy.com/app/numigi/odoo-project-addons/pullRequest?prid=4478774)

2019-11-13 14:18 UTC, ddufresne commented on project_task_reference/__init__.py
> +from . import models
![Codacy](https://app.codacy.com/assets/images/favicon.png) Issue found: ['.models' imported but unused](https://app.codacy.com/app/numigi/odoo-project-addons/pullRequest?prid=4478774)

2019-11-13 14:18 UTC, ddufresne commented on project_task_reference/models/project_task.py
> +from odoo import api, models, _
![Codacy](https://app.codacy.com/assets/images/favicon.png) Issue found: [Unused api imported from odoo](https://app.codacy.com/app/numigi/odoo-project-addons/pullRequest?prid=4478774)

2019-11-13 19:56 UTC, foutoucour approved these changes

2019-11-13 19:56 UTC, merged